# Generated by Django 3.1.1 on 2020-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KalamRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='NA', max_length=25, unique=True)),
                ('school', models.EmailField(default='unknown', max_length=25)),
                ('name', models.CharField(default='anonymous', max_length=255)),
                ('slot', models.CharField(default='00:00', max_length=100)),
                ('date', models.CharField(default='000000', max_length=100)),
                ('mobile', models.CharField(default='0000000000', max_length=10, unique=True)),
                ('payment', models.BooleanField(default=False)),
                ('payment_amount', models.BooleanField(default=0)),
            ],
        ),
    ]
