# Generated by Django 3.1.1 on 2020-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalamregistration',
            name='school',
            field=models.CharField(default='unknown', max_length=25),
        ),
    ]
