# Generated by Django 3.1.1 on 2020-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0003_auto_20200921_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalamregistration',
            name='payment_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
