# Generated by Django 3.1.1 on 2020-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0004_kalamregistration_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalamregistration',
            name='order_id',
            field=models.CharField(default='nor ordered', max_length=255, unique=True),
        ),
    ]
