# Generated by Django 3.1.1 on 2020-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0005_kalamregistration_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalamregistration',
            name='signature',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
