# Generated by Django 3.1.1 on 2020-09-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0007_bookafreetrial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeTInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='NA', max_length=25, unique=True)),
            ],
        ),
    ]
