# Generated by Django 3.1.1 on 2020-09-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalamlabs', '0008_getintouch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalamregistration',
            name='date',
        ),
        migrations.RemoveField(
            model_name='kalamregistration',
            name='slot',
        ),
    ]
